param(
  [string]$ManifestPath = "../android/app/src/main/AndroidManifest.xml",
  [string]$NetworkConfigPath = "../android/app/src/main/res/xml/network_security_config.xml",
  [string]$LocalPropertiesPath = "../android/local.properties"
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$manifestFull = Resolve-Path (Join-Path $scriptDir $ManifestPath) -ErrorAction SilentlyContinue

if (-not $manifestFull) {
  Write-Error "No se encontro AndroidManifest.xml. Ejecuta primero: npm run android:add"
  exit 1
}

$manifestFile = $manifestFull.Path
$networkFile = Join-Path $scriptDir $NetworkConfigPath
$networkDir = Split-Path -Parent $networkFile
$localPropertiesFile = Join-Path $scriptDir $LocalPropertiesPath

if (-not (Test-Path $networkDir)) {
  New-Item -ItemType Directory -Path $networkDir -Force | Out-Null
}

Copy-Item -Path (Join-Path $scriptDir "../android-config/network_security_config.xml") -Destination $networkFile -Force

$xml = Get-Content $manifestFile -Raw

if ($xml -notmatch 'android.permission.INTERNET') {
  $xml = $xml -replace '<manifest([^>]*)>', '<manifest$1>`r`n    <uses-permission android:name="android.permission.INTERNET" />`r`n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />'
}

if ($xml -notmatch 'usesCleartextTraffic') {
  $xml = $xml -replace '<application\s+', '<application android:usesCleartextTraffic="true" android:networkSecurityConfig="@xml/network_security_config" '
}

Set-Content -Path $manifestFile -Value $xml -Encoding UTF8

function Get-AndroidSdkPath {
  $candidates = @()

  if ($env:ANDROID_HOME) {
    $candidates += $env:ANDROID_HOME
  }

  if ($env:ANDROID_SDK_ROOT) {
    $candidates += $env:ANDROID_SDK_ROOT
  }

  if ($env:LOCALAPPDATA) {
    $candidates += (Join-Path $env:LOCALAPPDATA "Android\Sdk")
  }

  if ($env:USERPROFILE) {
    $candidates += (Join-Path $env:USERPROFILE "AppData\Local\Android\Sdk")
  }

  Get-ChildItem "C:\Users" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $candidates += (Join-Path $_.FullName "AppData\Local\Android\Sdk")
  }

  foreach ($candidate in ($candidates | Where-Object { $_ } | Select-Object -Unique)) {
    if (Test-Path $candidate) {
      return (Resolve-Path $candidate).Path
    }
  }

  return $null
}

function Convert-ToGradlePath([string]$PathValue) {
  return $PathValue.Replace('\', '\\').Replace(':', '\:')
}

$sdkPath = Get-AndroidSdkPath

if ($sdkPath) {
  $escapedSdkPath = Convert-ToGradlePath $sdkPath
  $localPropertiesContent = @(
    "## Auto-generated by scripts/apply-android-config.ps1",
    "sdk.dir=$escapedSdkPath"
  )

  Set-Content -Path $localPropertiesFile -Value $localPropertiesContent -Encoding ASCII
  Write-Output "SDK Android detectado en: $sdkPath"
} else {
  Write-Warning "No se encontro Android SDK automaticamente. Configura ANDROID_HOME o revisa android/local.properties."
}

Write-Output "Configuracion Android aplicada."
